# Generated by Django 5.0.6 on 2024-06-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0002_alter_link_title_alter_link_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
    ]
