# Generated by Django 5.0.6 on 2024-06-07 08:10

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/daluxpssk/image/upload/v1717744760/nobody_jm5djw.jpg', max_length=255, null=True, verbose_name='image')),
                ('location', models.CharField(choices=[('Allach', 'Allach'), ('Altstadt-Lehel', 'Altstadt-Lehel'), ('Aubing', 'Aubing'), ('Au-Haidhausen', 'Au-Haidhausen'), ('Berg am Laim', 'Berg am Laim'), ('Bogenhausen', 'Bogenhausen'), ('Fasangarten', 'Fasangarten'), ('Feldmoching-Hasenbergl', 'Feldmoching-Hasenbergl'), ('Forstenried', 'Forstenried'), ('Freimann', 'Freimann'), ('Fürstenried', 'Fürstenried'), ('Hadern', 'Hadern'), ('Harlaching', 'Harlaching'), ('Laim', 'Laim'), ('Langwied', 'Langwied'), ('Lochhausen', 'Lochhausen'), ('Ludwigsvorstadt-Isarvorstadt', 'Ludwigsvorstadt-Isarvorstadt'), ('Maxvorstadt', 'Maxvorstadt'), ('Milbertshofen-Am Hart', 'Milbertshofen-Am Hart'), ('Moosach', 'Moosach'), ('Neuhausen', 'Neuhausen'), ('Nymphenburg', 'Nymphenburg'), ('Obersendling', 'Obersendling'), ('Obergiesing', 'Obergiesing'), ('Pasing', 'Pasing'), ('Perlach', 'Perlach'), ('Ramersdorf', 'Ramersdorf'), ('Riem', 'Riem'), ('Schwabing', 'Schwabing'), ('Schwabing-West', 'Schwabing-West'), ('Schwanthalerhöhe', 'Schwanthalerhöhe'), ('Sendling', 'Sendling'), ('Sendling-Westpark', 'Sendling-Westpark'), ('Solln', 'Solln'), ('Thalkirchen', 'Thalkirchen'), ('Trudering', 'Trudering'), ('Untergiesing', 'Untergiesing'), ('Others', 'Others')], default='Others', max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('custom_location', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
