# Generated by Django 5.0.6 on 2024-05-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.IntegerField(choices=[(0, ''), (1, 'Bullying'), (2, 'Childcare'), (3, 'Child Safety'), (4, 'Cultural Traditions'), (5, 'Daycare'), (6, 'Education and Development'), (7, 'Healthcare'), (8, 'Legal and Administrative Processes'), (9, 'Nutrition'), (10, 'Parental Benefits'), (11, 'Parenting Advice'), (12, 'Pregnancy and Birth')], default=0),
        ),
    ]
