# Generated by Django 5.0.6 on 2024-05-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(0, ''), (1, 'Bullying'), (2, 'Child Safety'), (3, 'Childcare'), (4, 'Cultural Traditions'), (5, 'Education and Development'), (6, 'Healthcare'), (7, 'Legal and Administrative Processes'), (8, 'Nutrition'), (9, 'Parental Benefits'), (10, 'Parenting Advice'), (11, 'Pregnancy and Birth')], max_length=100),
        ),
    ]
